[project]
name = "axiom-launcher"
version = "0.16.0"
description = "A Minecraft launcher"
readme = "README.md"
authors = [
    { name = "Felix Qu", email = "quqi0414@163.com" }
]
requires-python = ">=3.12"
dependencies = [
    "requests>=2.34.2",
]

[project.scripts]
axiom-launcher = "axiom_launcher:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
